version: '3.8'


services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - cart
      - checkout
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  cart:
    build:
      context: ./cart
    expose:
      - "8081"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - 'SPRING_DATA_MONGODB_URI=mongodb://root:123@mongo:27017/cart_db?authsource=admin'

  checkout:
    build:
      context: ./checkout
    expose:
      - "8082"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  database:
    image: 'postgres:latest'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=checkout'
      - 'POSTGRES_PASSWORD=admin'
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
